### ISSUE TITLE
Get a depth dataset from custom rgb dataset

### ISSUE THREAD

**Issue by czeyveli1** [YvanYin/Metric3D#171]
Hello everyone,

I am trying to create a **metric depth dataset** using the **Replica RGB dataset**, but I am not entirely sure how to proceed with it. I don’t quite understand which code file I need to work on to achieve this.

Additionally, below are the config settings for the dataset I will be using:
```
dataset_name: 'replica'
camera_params:
  image_height: 680
  image_width: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5
  crop_edge: 0
```
In which file exactly should I set these parameters?
In short, how can I obtain the depth outputs? I would appreciate it if you could help me with this.
